INSERT INTO categories SET id = 'lamdep', name = 'Làm đẹp';
INSERT INTO categories SET id = 'sachbaovantho', name = 'Sách báo văn thơ';
INSERT INTO categories SET id = 'otoxemay', name = 'Ô tô xe máy';
INSERT INTO categories SET id = 'amnhac', name = 'Âm nhạc';
INSERT INTO categories SET id = 'giaitri', name = 'Giải trí';
INSERT INTO categories SET id = 'nhadat', name = 'Nhà đất';
INSERT INTO categories SET id = 'dautu-quyhoach', name = 'Đầu tư - Quy hoạch';
INSERT INTO categories SET id = 'tinhyeu', name = 'Tình yêu';
INSERT INTO categories SET id = 'thitruong', name = 'Thị trường';
INSERT INTO categories SET id = 'kinhte', name = 'Kinh tế';
INSERT INTO categories SET id = 'suckhoe', name = 'Sức khỏe';
INSERT INTO categories SET id = 'hocbong', name = 'Học bổng';
INSERT INTO categories SET id = 'khonggiansong', name = 'Không gian sống';
INSERT INTO categories SET id = 'cntt', name = 'Công nghệ thông tin';
INSERT INTO categories SET id = 'khcn', name = 'Khoa học công nghệ';
INSERT INTO categories SET id = 'sankhau', name = 'Sân khấu';
INSERT INTO categories SET id = 'vanhoa', name = 'Văn hóa';
INSERT INTO categories SET id = 'dulich', name = 'Du lịch';
INSERT INTO categories SET id = 'tuyendung', name = 'Tuyển dụng';
INSERT INTO categories SET id = 'thietbi-phancung', name = 'Thiết bị - Phần cứng';
INSERT INTO categories SET id = 'hinhsu', name = 'Hình sự';
INSERT INTO categories SET id = 'daotao', name = 'Đào tạo';
INSERT INTO categories SET id = 'thethao', name = 'Thể thao';
INSERT INTO categories SET id = 'phapluat', name = 'Pháp luật';
INSERT INTO categories SET id = 'amthuc', name = 'Ẩm thực';
INSERT INTO categories SET id = 'khoahoc-tunhien', name = 'Khoa học - Tự nhiên';
INSERT INTO categories SET id = 'taichinh', name = 'Tài chính';
INSERT INTO categories SET id = 'anninh', name = 'An ninh';
INSERT INTO categories SET id = 'thoitrang', name = 'Thời trang';
INSERT INTO categories SET id = 'thegioi', name = 'Thế giới';
INSERT INTO categories SET id = 'chungkhoan', name = 'Chứng khoán';
INSERT INTO categories SET id = 'giaoduc', name = 'Giáo dục';
INSERT INTO categories SET id = 'laodong', name = 'Lao động';
INSERT INTO categories SET id = 'doinoi-doingoai', name = 'Đối nội - Đối ngoại';
INSERT INTO categories SET id = 'thoisu', name = 'Thời sự';
INSERT INTO categories SET id = 'quanvot', name = 'Quần vợt';
INSERT INTO categories SET id = 'xahoi', name = 'Xã hội';
INSERT INTO categories SET id = 'bongda', name = 'Bóng đá';